# permissions for end users to edit appdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: lyrid-operator
    app.kubernetes.io/managed-by: kustomize
  name: appdeployment-editor-role
rules:
- apiGroups:
  - apps.lyrid.io
  resources:
  - appdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.lyrid.io
  resources:
  - appdeployments/status
  verbs:
  - get
