apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "lyrid-operator.fullname" . }}-role
rules:
  - apiGroups: ["apps.lyrid.io"]
    resources: ["appdeployments", "appmodules", "deploymentendpoints", "functions", "functioncodes", "revisions", "subdomains"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: [ "apps.lyrid.io" ]
    resources: [ "appdeployments/finalizers", "appmodules/finalizers", "deploymentendpoints/finalizers", "functions/finalizers", "functioncodes/finalizers", "revisions/finalizers", "subdomains/finalizers" ]
    verbs: [ "update" ]
  - apiGroups: [ "apps.lyrid.io" ]
    resources: [ "appdeployments/status", "appmodules/status", "deploymentendpoints/status", "functions/status", "functioncodes/status", "revisions/status", "subdomains/status" ]
    verbs: [ "get", "patch", "update" ]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "replicasets"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [ "" ]
    resources: [ "services" ]
    verbs: [ "create", "delete", "get", "list", "patch", "update", "watch" ]
