apiVersion: apps.lyrid.io/v1alpha1
kind: AppDeployment
metadata:
  name: swift-web-app-no2
  namespace: lyrid-9cc8b789-e6df-434a-afbb-371e8280ec1a
spec:
  bearerToken: ""
  image: harbor.apsoutheast1.lyr.id/azhary/swift-web-app:2024-10-04
  replicas: 1
  ports:
    - name: http
      containerPort: 3000
      protocol: TCP
  resources:
    requests:
      memory: 129Mi
      cpu: 101m
    limits:
      memory: 513Mi
      cpu: 501m
